'use strict';
// tests for hello
// Generated by serverless-mocha-plugin

const mod = require('../fnHello/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'hello' });

describe('hello', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', (done) => {
    wrapped.run({
      foo: 'bar',
    })
      .then((response) => {
        expect(response.event.foo).to.equal('bar');
        expect(response.message).to.match(/successful/);
        done();
      })
      .catch(done);
  });
});
